# Generated by Django 5.2.17 on 2026-10-02 03:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.CharField(max_length=160, primary_key=True, serialize=False)),
                ('schema_version', models.CharField(default='study-workbench.core.v0.1', max_length=80)),
            ],
            options={
                'db_table': 'swb_household',
            },
        ),
        migrations.CreateModel(
            name='RevisionRecord',
            fields=[
                ('revision_id', models.CharField(max_length=160, primary_key=True, serialize=False)),
                ('revision_no', models.PositiveIntegerField()),
                ('content_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('dependency_heads', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'swb_revisionrecord',
            },
        ),
        migrations.CreateModel(
            name='EntityRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('knowledge', 'Knowledge'), ('method', 'Method'), ('question_type', 'Question type'), ('question', 'Question'), ('observation', 'Observation'), ('attempt', 'Attempt'), ('assessment', 'Assessment'), ('erratum', 'Erratum'), ('region', 'Region'), ('knowledge_question', 'Knowledge question link'), ('method_question', 'Method question link'), ('question_type_link', 'Question type link'), ('learner', 'Learner')], max_length=32)),
                ('stable_id', models.CharField(max_length=160)),
                ('identity', models.JSONField()),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entities', to='persistence.household')),
            ],
            options={
                'db_table': 'swb_entityrecord',
            },
        ),
        migrations.CreateModel(
            name='ImageRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stable_id', models.CharField(max_length=160)),
                ('sha256', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='persistence.household')),
            ],
            options={
                'db_table': 'swb_imagerecord',
            },
        ),
        migrations.CreateModel(
            name='RequestReceipt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_key', models.CharField(max_length=160)),
                ('operation', models.CharField(choices=[('stage', 'Stage'), ('review', 'Review')], max_length=16)),
                ('request_hash', models.CharField(max_length=64)),
                ('result', models.JSONField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_workbench_request_receipts', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_receipts', to='persistence.household')),
            ],
            options={
                'db_table': 'swb_requestreceipt',
            },
        ),
        migrations.CreateModel(
            name='ReviewProjection',
            fields=[
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='review_projection', serialize=False, to='persistence.revisionrecord')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('stale', 'Stale'), ('withdrawn', 'Withdrawn')], default='draft', max_length=16)),
            ],
            options={
                'db_table': 'swb_reviewprojection',
            },
        ),
        migrations.AddField(
            model_name='revisionrecord',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='persistence.entityrecord'),
        ),
        migrations.AddField(
            model_name='revisionrecord',
            name='original_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='region_revisions', to='persistence.imagerecord'),
        ),
        migrations.AddField(
            model_name='revisionrecord',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_revisions', to='persistence.revisionrecord'),
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('withdraw', 'Withdraw')], max_length=16)),
                ('reason', models.TextField()),
                ('expected_dependencies', models.JSONField(default=list)),
                ('request_key', models.CharField(max_length=160)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_workbench_review_decisions', to=settings.AUTH_USER_MODEL)),
                ('expected_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='persistence.reviewdecision')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_decisions', to='persistence.household')),
                ('expected_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expected_by_decisions', to='persistence.revisionrecord')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_decisions', to='persistence.revisionrecord')),
            ],
            options={
                'db_table': 'swb_reviewdecision',
                'constraints': [models.UniqueConstraint(fields=('revision', 'expected_decision'), name='swb_dec_revision_expected_uniq', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='EvidenceRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slot', models.CharField(choices=[('source', 'Source'), ('answer', 'Answer'), ('method', 'Method'), ('process', 'Process'), ('calculation', 'Calculation'), ('notation', 'Notation')], max_length=16)),
                ('sequence', models.PositiveIntegerField()),
                ('purpose', models.CharField(choices=[('question', 'Question'), ('handwriting', 'Handwriting'), ('formula', 'Formula'), ('diagram', 'Diagram'), ('definition', 'Definition'), ('other', 'Other')], max_length=16)),
                ('granularity', models.CharField(choices=[('whole_image', 'Whole image'), ('region', 'Region')], max_length=16)),
                ('region_missing', models.BooleanField()),
                ('gaps', models.JSONField(default=list)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='persistence.imagerecord')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence_regions', to='persistence.revisionrecord')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='persistence.revisionrecord')),
            ],
            options={
                'db_table': 'swb_evidencerecord',
            },
        ),
        migrations.AddField(
            model_name='entityrecord',
            name='head_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='head_for_entities', to='persistence.revisionrecord'),
        ),
        migrations.AddField(
            model_name='entityrecord',
            name='published_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_for_entities', to='persistence.revisionrecord'),
        ),
        migrations.CreateModel(
            name='RevisionDependency',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('parent_question', 'Parent question'), ('parent_method', 'Parent method'), ('question_erratum', 'Question erratum'), ('attempt_question', 'Attempt question'), ('attempt_observation', 'Attempt observation'), ('assessment_attempt', 'Assessment attempt'), ('assessment_question', 'Assessment question'), ('assessment_erratum', 'Assessment erratum'), ('erratum_target', 'Erratum target'), ('link_question', 'Link question'), ('link_knowledge', 'Link knowledge'), ('link_method', 'Link method'), ('link_question_type', 'Link question type')], max_length=32)),
                ('position', models.PositiveIntegerField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_dependencies', to='persistence.revisionrecord')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_dependencies', to='persistence.revisionrecord')),
            ],
            options={
                'db_table': 'swb_revisiondependency',
            },
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('reviewer', 'Reviewer'), ('viewer', 'Viewer')], max_length=16)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='persistence.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_workbench_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'swb_householdmember',
                'constraints': [models.UniqueConstraint(fields=('household', 'user'), name='swb_member_house_user_uniq'), models.CheckConstraint(condition=models.Q(('role__in', ('owner', 'reviewer', 'viewer'))), name='swb_member_role_valid')],
            },
        ),
        migrations.AddConstraint(
            model_name='imagerecord',
            constraint=models.UniqueConstraint(fields=('household', 'stable_id'), name='swb_image_house_stable_uniq'),
        ),
        migrations.AddConstraint(
            model_name='imagerecord',
            constraint=models.UniqueConstraint(fields=('household', 'sha256'), name='swb_image_house_sha_uniq'),
        ),
        migrations.AddConstraint(
            model_name='imagerecord',
            constraint=models.CheckConstraint(condition=models.Q(('sha256__regex', '^[0-9a-f]{64}$')), name='swb_image_sha_valid'),
        ),
        migrations.AddConstraint(
            model_name='requestreceipt',
            constraint=models.UniqueConstraint(fields=('household', 'request_key'), name='swb_receipt_house_request_uniq'),
        ),
        migrations.AddConstraint(
            model_name='requestreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('operation__in', ('stage', 'review'))), name='swb_receipt_op_valid'),
        ),
        migrations.AddConstraint(
            model_name='requestreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('request_hash__regex', '^[0-9a-f]{64}$')), name='swb_receipt_hash_valid'),
        ),
        migrations.AddField(
            model_name='reviewprojection',
            name='decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projections', to='persistence.reviewdecision'),
        ),
        migrations.AddConstraint(
            model_name='revisionrecord',
            constraint=models.UniqueConstraint(fields=('entity', 'revision_no'), name='swb_rev_entity_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='revisionrecord',
            constraint=models.CheckConstraint(condition=models.Q(('revision_no__gt', 0)), name='swb_rev_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='revisionrecord',
            constraint=models.CheckConstraint(condition=models.Q(('content_hash__regex', '^[0-9a-f]{64}$')), name='swb_rev_hash_valid'),
        ),
        migrations.AddConstraint(
            model_name='reviewdecision',
            constraint=models.UniqueConstraint(fields=('household', 'request_key'), name='swb_dec_house_request_uniq'),
        ),
        migrations.AddConstraint(
            model_name='reviewdecision',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ('accept', 'reject', 'withdraw'))), name='swb_dec_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='evidencerecord',
            constraint=models.UniqueConstraint(fields=('source', 'slot', 'sequence'), name='swb_evid_source_slot_seq_uniq'),
        ),
        migrations.AddConstraint(
            model_name='evidencerecord',
            constraint=models.CheckConstraint(condition=models.Q(('slot__in', ('source', 'answer', 'method', 'process', 'calculation', 'notation'))), name='swb_evid_slot_valid'),
        ),
        migrations.AddConstraint(
            model_name='evidencerecord',
            constraint=models.CheckConstraint(condition=models.Q(('purpose__in', ('question', 'handwriting', 'formula', 'diagram', 'definition', 'other'))), name='swb_evid_purpose_valid'),
        ),
        migrations.AddConstraint(
            model_name='evidencerecord',
            constraint=models.CheckConstraint(condition=models.Q(('granularity__in', ('whole_image', 'region'))), name='swb_evid_gran_valid'),
        ),
        migrations.AddConstraint(
            model_name='evidencerecord',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gt', 0)), name='swb_evid_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='entityrecord',
            constraint=models.UniqueConstraint(fields=('household', 'kind', 'stable_id'), name='swb_entity_identity_uniq'),
        ),
        migrations.AddConstraint(
            model_name='entityrecord',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ('knowledge', 'method', 'question_type', 'question', 'observation', 'attempt', 'assessment', 'erratum', 'region', 'knowledge_question', 'method_question', 'question_type_link', 'learner'))), name='swb_entity_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='revisiondependency',
            constraint=models.UniqueConstraint(fields=('source', 'role', 'position'), name='swb_dep_source_role_pos_uniq'),
        ),
        migrations.AddConstraint(
            model_name='revisiondependency',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ('parent_question', 'parent_method', 'question_erratum', 'attempt_question', 'attempt_observation', 'assessment_attempt', 'assessment_question', 'assessment_erratum', 'erratum_target', 'link_question', 'link_knowledge', 'link_method', 'link_question_type'))), name='swb_dep_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='revisiondependency',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 0)), name='swb_dep_position_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='reviewprojection',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('draft', 'accepted', 'rejected', 'stale', 'withdrawn'))), name='swb_projection_state_valid'),
        ),
    ]
