# Generated by Django 5.2.17 on 2026-10-02 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0003_web_receipts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='requestreceipt',
            name='swb_receipt_op_valid',
        ),
        migrations.AlterField(
            model_name='requestreceipt',
            name='operation',
            field=models.CharField(choices=[('stage', 'Stage'), ('review', 'Review'), ('web_material', 'Material'), ('web_upload', 'Upload'), ('web_order', 'Page order'), ('web_question', 'Question'), ('web_record', 'Business record')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='requestreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('operation__in', ('stage', 'review', 'web_material', 'web_upload', 'web_order', 'web_question', 'web_record'))), name='swb_receipt_op_valid'),
        ),
    ]
