# Generated by Django 5.2.17 on 2026-10-02 11:35

import django.db.models.constraints
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persistence', '0002_postgresql_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persistence.household')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSource',
            fields=[
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='persistence.revisionrecord')),
                ('original_number', models.CharField(blank=True, max_length=80)),
                ('sources', models.JSONField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workbench_web.materialset')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('original_name', models.CharField(max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persistence.imagerecord')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='workbench_web.materialset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('material', 'position'), name='swb_web_page_position'), models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='swb_web_position_positive')],
            },
        ),
        migrations.CreateModel(
            name='PagePreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotation', models.PositiveSmallIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('storage_key', models.CharField(max_length=240)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='web_previews', to='persistence.imagerecord')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('image', 'rotation'), name='swb_web_preview_rotation'), models.CheckConstraint(condition=models.Q(('rotation__in', (0, 90, 180, 270))), name='swb_web_rotation_valid'), models.CheckConstraint(condition=models.Q(('sha256__regex', '^[0-9a-f]{64}$')), name='swb_web_preview_hash')],
            },
        ),
    ]
