# Generated by Django 5.2.17 on 2026-10-03 12:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


GUARD = '''
CREATE FUNCTION swb_derivative_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP <> 'INSERT' THEN RAISE EXCEPTION 'derivatives are append-only'; END IF;
  IF NOT EXISTS (
    SELECT 1 FROM workbench_web_materialpage p
    JOIN workbench_web_materialset m ON m.id=p.material_id
    JOIN swb_imagerecord i ON i.id=p.image_id
    WHERE p.id=NEW.page_id AND i.id=NEW.original_image_id
      AND i.household_id=m.household_id AND i.sha256=NEW.original_sha256
  ) THEN RAISE EXCEPTION 'derivative original mismatch'; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER swb_derivative_guard BEFORE INSERT OR UPDATE OR DELETE ON workbench_web_imagederivative
FOR EACH ROW EXECUTE FUNCTION swb_derivative_guard();
'''
REVERSE='''DROP TRIGGER swb_derivative_guard ON workbench_web_imagederivative;
DROP FUNCTION swb_derivative_guard();'''


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0004_business_receipts'),
        ('workbench_web', '0002_source_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDerivative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('crop', '裁切'), ('erase', '手动遮白'), ('contrast', '对比度增强')], max_length=16)),
                ('parameters', models.JSONField()),
                ('original_sha256', models.CharField(max_length=64)),
                ('sha256', models.CharField(max_length=64)),
                ('storage_key', models.CharField(max_length=240)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('lossy_description', models.CharField(max_length=1000)),
                ('request_key', models.CharField(max_length=160)),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivatives', to='persistence.imagerecord')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivatives', to='workbench_web.materialpage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('page', 'created_by', 'request_key'), name='swb_derivative_request'), models.CheckConstraint(condition=models.Q(('operation__in', ('crop', 'erase', 'contrast'))), name='swb_derivative_operation'), models.CheckConstraint(condition=models.Q(('height__gt', 0), ('width__gt', 0)), name='swb_derivative_size')],
            },
        ),
        migrations.RunSQL(GUARD, REVERSE),
    ]
