# Generated by Django 5.2.17 on 2026-10-04 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

SQL = """
CREATE FUNCTION swb_guard_page_reading() RETURNS trigger AS $$
DECLARE latest bigint; latest_no integer; original jsonb; original_hash text;
    stable_image text; page_house text; part jsonb; box jsonb; mapped jsonb;
    x0 numeric; y0 numeric; x1 numeric; y1 numeric; w numeric; h numeric; angle integer;
BEGIN
    PERFORM id FROM swb_household WHERE id=NEW.household_id FOR UPDATE;
    SELECT i.payload,i.sha256,i.stable_id,m.household_id INTO original,original_hash,stable_image,page_house
        FROM workbench_web_materialpage p JOIN workbench_web_materialset m ON m.id=p.material_id
        JOIN swb_imagerecord i ON i.id=p.image_id WHERE p.id=NEW.page_id;
    IF page_house IS DISTINCT FROM NEW.household_id OR original_hash IS DISTINCT FROM NEW.original_sha256 THEN
        RAISE EXCEPTION 'page reading source mismatch' USING ERRCODE='23514';
    END IF;
    SELECT id,revision_no INTO latest,latest_no FROM workbench_web_pagereadingrevision
        WHERE page_id=NEW.page_id ORDER BY revision_no DESC LIMIT 1;
    IF NEW.previous_id IS DISTINCT FROM latest OR NEW.revision_no IS DISTINCT FROM COALESCE(latest_no,0)+1 THEN
        RAISE EXCEPTION 'page reading must append current version' USING ERRCODE='23514';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM swb_householdmember m JOIN auth_user u ON u.id=m.user_id
        WHERE m.household_id=NEW.household_id AND m.user_id=NEW.created_by_id
        AND m.role IN ('owner','reviewer') AND u.is_active) THEN
        RAISE EXCEPTION 'page reading author unauthorized' USING ERRCODE='23514';
    END IF;
    IF btrim(NEW.basis)='' OR length(NEW.basis)>1000 OR length(NEW.pending_items)>4000
        OR (NEW.reading='needs_retake' AND btrim(NEW.pending_items)='') THEN
        RAISE EXCEPTION 'page reading requires human basis and retake reason' USING ERRCODE='23514';
    END IF;
    IF jsonb_typeof(NEW.partitions) IS DISTINCT FROM 'array' THEN
        RAISE EXCEPTION 'page partitions must be an array' USING ERRCODE='23514';
    END IF;
    IF jsonb_array_length(NEW.partitions)>100 OR (NEW.coverage='complete' AND
        (jsonb_array_length(NEW.partitions)=0 OR NEW.pending_items<>'')) THEN
        RAISE EXCEPTION 'incomplete page partitions' USING ERRCODE='23514';
    END IF;
    w=(original->>'width')::numeric; h=(original->>'height')::numeric;
    FOR part IN SELECT value FROM jsonb_array_elements(NEW.partitions) LOOP
        IF jsonb_typeof(part) IS DISTINCT FROM 'object' OR
            COALESCE(part->>'kind','') NOT IN ('theory','question','diagram','handwriting','unknown') OR
            part->>'page_id' IS DISTINCT FROM NEW.page_id::text OR
            part->>'image_id' IS DISTINCT FROM stable_image OR
            part->>'original_sha256' IS DISTINCT FROM original_hash OR
            jsonb_typeof(part->'rotation') IS DISTINCT FROM 'number' OR
            COALESCE(part->>'rotation','') NOT IN ('0','90','180','270') OR
            (NEW.coverage='complete' AND part->>'kind'='unknown') THEN
            RAISE EXCEPTION 'page partition identity or type invalid' USING ERRCODE='23514';
        END IF;
        angle=(part->>'rotation')::integer;
        IF NOT EXISTS (SELECT 1 FROM workbench_web_pagepreview v
            JOIN workbench_web_materialpage p ON p.image_id=v.image_id
            WHERE p.id=NEW.page_id AND v.rotation=angle AND v.sha256=part->>'preview_sha256') THEN
            RAISE EXCEPTION 'page partition preview mismatch' USING ERRCODE='23514';
        END IF;
        box=part->'display_bbox';
        IF jsonb_typeof(box) IS DISTINCT FROM 'array' THEN
            RAISE EXCEPTION 'page partition box invalid' USING ERRCODE='23514';
        END IF;
        IF jsonb_array_length(box)<>4 OR EXISTS (SELECT 1 FROM jsonb_array_elements(box) b
            WHERE jsonb_typeof(b) IS DISTINCT FROM 'number') THEN
            RAISE EXCEPTION 'page partition box invalid' USING ERRCODE='23514';
        END IF;
        x0=(box->>0)::numeric; y0=(box->>1)::numeric; x1=(box->>2)::numeric; y1=(box->>3)::numeric;
        IF x0<>trunc(x0) OR y0<>trunc(y0) OR x1<>trunc(x1) OR y1<>trunc(y1) THEN
            RAISE EXCEPTION 'page partition coordinates must use whole pixels' USING ERRCODE='23514';
        END IF;
        IF NOT (x0>=0 AND y0>=0 AND x1>x0 AND y1>y0 AND
            x1<=CASE WHEN angle IN (90,270) THEN h ELSE w END AND
            y1<=CASE WHEN angle IN (90,270) THEN w ELSE h END) THEN
            RAISE EXCEPTION 'page partition box outside image' USING ERRCODE='23514';
        END IF;
        mapped=CASE angle WHEN 0 THEN jsonb_build_array(x0,y0,x1,y1)
            WHEN 90 THEN jsonb_build_array(y0,h-x1,y1,h-x0)
            WHEN 180 THEN jsonb_build_array(w-x1,h-y1,w-x0,h-y0)
            WHEN 270 THEN jsonb_build_array(w-y1,x0,w-y0,x1) END;
        IF part->'original_bbox' IS DISTINCT FROM mapped THEN
            RAISE EXCEPTION 'page partition original coordinates mismatch' USING ERRCODE='23514';
        END IF;
    END LOOP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER swb_page_reading_insert BEFORE INSERT ON workbench_web_pagereadingrevision
    FOR EACH ROW EXECUTE FUNCTION swb_guard_page_reading();
CREATE TRIGGER swb_page_reading_immutable BEFORE UPDATE OR DELETE ON workbench_web_pagereadingrevision
    FOR EACH ROW EXECUTE FUNCTION swb_reject_immutable_change();
"""
REVERSE = """
DROP TRIGGER swb_page_reading_immutable ON workbench_web_pagereadingrevision;
DROP TRIGGER swb_page_reading_insert ON workbench_web_pagereadingrevision;
DROP FUNCTION swb_guard_page_reading();
"""

class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0004_business_receipts'),
        ('workbench_web', '0003_imagederivative'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageReadingRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_no', models.PositiveIntegerField()),
                ('original_sha256', models.CharField(max_length=64)),
                ('reading', models.CharField(choices=[('unread', '未阅读'), ('read', '已阅读'), ('needs_retake', '待重拍')], max_length=16)),
                ('coverage', models.CharField(choices=[('partial', '待补分区'), ('complete', '已逐项核对分区')], max_length=16)),
                ('partitions', models.JSONField(default=list)),
                ('pending_items', models.TextField(blank=True)),
                ('basis', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persistence.household')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reading_revisions', to='workbench_web.materialpage')),
                ('previous', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workbench_web.pagereadingrevision')),
            ],
            options={
                'ordering': ('-revision_no',),
                'constraints': [models.UniqueConstraint(fields=('page', 'revision_no'), name='swb_page_reading_version'), models.CheckConstraint(condition=models.Q(('revision_no__gt', 0)), name='swb_page_reading_positive'), models.CheckConstraint(condition=models.Q(('reading__in', ('unread', 'read', 'needs_retake'))), name='swb_page_reading_state'), models.CheckConstraint(condition=models.Q(('coverage__in', ('partial', 'complete'))), name='swb_page_reading_coverage'), models.CheckConstraint(condition=models.Q(('coverage', 'partial'), ('reading', 'read'), _connector='OR'), name='swb_page_reading_complete_read')],
            },
        ),
        migrations.RunSQL(SQL, REVERSE),
    ]
