# Generated by Django 5.2.17 on 2026-10-05 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

SQL = """
CREATE FUNCTION swb_classification_insert_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE old_id bigint; old_version integer; house text;
BEGIN
  SELECT household_id INTO house FROM workbench_web_materialset WHERE id=NEW.material_id FOR UPDATE;
  SELECT id,version INTO old_id,old_version FROM workbench_web_materialclassificationrevision
    WHERE material_id=NEW.material_id ORDER BY version DESC LIMIT 1;
  IF NEW.previous_id IS DISTINCT FROM old_id OR NEW.version IS DISTINCT FROM COALESCE(old_version,0)+1 THEN
    RAISE EXCEPTION 'Classification must append the current history';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM swb_householdmember m JOIN auth_user u ON u.id=m.user_id
    WHERE m.household_id=house AND m.user_id=NEW.created_by_id AND m.role IN ('owner','reviewer') AND u.is_active)
    OR btrim(NEW.reason)='' OR length(NEW.reason)>1000 OR btrim(NEW.request_key)='' THEN
    RAISE EXCEPTION 'Classification requires an authorized author and reason';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER swb_classification_insert BEFORE INSERT ON workbench_web_materialclassificationrevision
  FOR EACH ROW EXECUTE FUNCTION swb_classification_insert_guard();
CREATE TRIGGER swb_classification_immutable BEFORE UPDATE OR DELETE ON workbench_web_materialclassificationrevision
  FOR EACH ROW EXECUTE FUNCTION swb_reject_immutable_change();
"""
REVERSE = """
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM workbench_web_materialclassificationrevision) THEN
    RAISE EXCEPTION 'Restore a matching backup rather than discarding classification history';
  END IF;
END $$;
DROP TRIGGER swb_classification_immutable ON workbench_web_materialclassificationrevision;
DROP TRIGGER swb_classification_insert ON workbench_web_materialclassificationrevision;
DROP FUNCTION swb_classification_insert_guard();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('workbench_web', '0004_page_reading_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialClassificationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=1000)),
                ('request_key', models.CharField(max_length=160)),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classifications', to='workbench_web.materialset')),
                ('previous', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workbench_web.materialclassificationrevision')),
            ],
            options={
                'ordering': ('-version',),
                'constraints': [models.UniqueConstraint(fields=('material', 'version'), name='swb_material_class_version'), models.UniqueConstraint(fields=('material', 'request_key'), name='swb_material_class_request'), models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='swb_material_class_positive'), models.CheckConstraint(condition=models.Q(('subject__in', ('unknown', 'mathematics', 'chinese', 'english', 'physics', 'chemistry', 'biology', 'history', 'geography', 'politics', 'science', 'other'))), name='swb_material_class_subject')],
            },
        ),
        migrations.RunSQL(SQL, REVERSE),
    ]
