# Generated by Django 5.2.17 on 2026-10-04 12:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workbench_web', '0004_page_reading_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_key', models.CharField(max_length=160)),
                ('fingerprint', models.CharField(max_length=64)),
                ('input', models.JSONField(default=dict)),
                ('state', models.CharField(default='needs_review', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('source_stamp', models.CharField(max_length=64)),
                ('result', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('started_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_jobs', to='workbench_web.materialset')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=40)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='workflows.workflowjob')),
            ],
            options={
                'ordering': ('version',),
            },
        ),
        migrations.AddConstraint(
            model_name='workflowjob',
            constraint=models.UniqueConstraint(fields=('material', 'request_key'), name='swb_workflow_request_unique'),
        ),
        migrations.AddConstraint(
            model_name='workflowjob',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('needs_review', 'ready', 'queued', 'running', 'output_check', 'complete', 'failed', 'cancelled'))), name='swb_workflow_state'),
        ),
        migrations.AddConstraint(
            model_name='workflowjob',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='swb_workflow_version'),
        ),
        migrations.AddConstraint(
            model_name='workflowevent',
            constraint=models.UniqueConstraint(fields=('job', 'version'), name='swb_workflow_event_version'),
        ),
    ]
