# Generated by Django 5.2.17 on 2026-10-04 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0004_business_receipts'),
        ('workflows', '0002_audit_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=160)),
                ('version', models.PositiveIntegerField(default=1)),
                ('base_stamp', models.CharField(blank=True, max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persistence.household')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('household', 'actor', 'key'), name='swb_workspace_draft_unique')],
            },
        ),
    ]
