# Generated by Django 5.2.17 on 2026-10-02 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persistence', '0004_business_receipts'),
        ('printing', '0002_append_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportArchiveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_storage_key', models.CharField(max_length=300)),
                ('archive_storage_key', models.CharField(max_length=360, unique=True)),
                ('manifest_sha256', models.CharField(max_length=64)),
                ('archive_sha256', models.CharField(max_length=64)),
                ('file_hashes', models.JSONField()),
                ('reason', models.CharField(max_length=1000)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('archived_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_archives', to='persistence.household')),
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='local_archive', to='printing.exportsnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='ExportRetirementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(max_length=300)),
                ('archive_storage_key', models.CharField(max_length=360)),
                ('manifest_sha256', models.CharField(max_length=64)),
                ('archive_sha256', models.CharField(max_length=64)),
                ('file_hashes', models.JSONField()),
                ('reason', models.CharField(max_length=1000)),
                ('retired_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_retirements', to='persistence.household')),
                ('retired_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='local_retirement', to='printing.exportsnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='RetentionPolicyRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_no', models.PositiveIntegerField()),
                ('archive_after_days', models.PositiveIntegerField(blank=True, null=True)),
                ('delete_after_days', models.PositiveIntegerField(blank=True, null=True)),
                ('reason', models.CharField(max_length=1000)),
                ('request_key', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retention_policies', to='persistence.household')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_revisions', to='operations.retentionpolicyrevision')),
            ],
            options={
                'ordering': ('household_id', 'revision_no'),
                'constraints': [models.UniqueConstraint(fields=('household', 'revision_no'), name='ops_policy_version'), models.UniqueConstraint(fields=('household', 'request_key'), name='ops_policy_request'), models.CheckConstraint(condition=models.Q(('revision_no__gt', 0)), name='ops_policy_positive'), models.CheckConstraint(condition=models.Q(('delete_after_days__isnull', True), models.Q(('archive_after_days__isnull', False), ('delete_after_days__gte', models.F('archive_after_days'))), _connector='OR'), name='ops_policy_archive_before_delete')],
            },
        ),
        migrations.CreateModel(
            name='WorkTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('manual_entry', '手工录入'), ('model_correction', '模型结果人工修订')], max_length=24)),
                ('seconds', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=1000)),
                ('request_key', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('attempt_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timing_records', to='persistence.revisionrecord')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_timings', to='persistence.household')),
                ('question_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_timings', to='persistence.revisionrecord')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-recorded_at', '-pk'),
                'constraints': [models.UniqueConstraint(fields=('household', 'request_key'), name='ops_timing_request'), models.CheckConstraint(condition=models.Q(('kind__in', ('manual_entry', 'model_correction'))), name='ops_timing_kind_valid'), models.CheckConstraint(condition=models.Q(('seconds__gt', 0), ('seconds__lte', 604800)), name='ops_timing_seconds_valid')],
            },
        ),
    ]
