# Generated by Django 5.2.17 on 2026-10-02 18:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persistence', '0004_business_receipts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_no', models.PositiveIntegerField()),
                ('provider_label', models.CharField(max_length=120)),
                ('base_url', models.URLField(max_length=500)),
                ('model', models.CharField(max_length=160)),
                ('cloud_enabled', models.BooleanField(default=False)),
                ('outbound_scope', models.CharField(choices=[('reviewed_text', 'Reviewed text only'), ('selected_regions', 'Reviewed text and selected image regions')], default='reviewed_text', max_length=24)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=30)),
                ('max_output_tokens', models.PositiveSmallIntegerField(default=1000)),
                ('max_input_chars', models.PositiveSmallIntegerField(default=16000)),
                ('max_calls', models.PositiveSmallIntegerField(default=4)),
                ('batch_budget', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('input_price_per_million', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('output_price_per_million', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('reserved_per_call', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('non_billable_gateway', models.BooleanField(default=False)),
                ('currency', models.CharField(default='USD', editable=False, max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_ai_model_configs', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_model_configs', to='persistence.household')),
            ],
            options={
                'db_table': 'ai_modelconfig',
                'ordering': ('household_id', 'revision_no'),
            },
        ),
        migrations.CreateModel(
            name='ModelRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_snapshot', models.JSONField()),
                ('task_kind', models.CharField(choices=[('question', 'Question draft'), ('knowledge', 'Knowledge draft'), ('assessment', 'Attempt assessment draft'), ('variant', 'Variant question draft')], max_length=16)),
                ('question_revision_ids', models.JSONField(default=list)),
                ('source_revision_ids', models.JSONField(default=list)),
                ('selected_region_revision_ids', models.JSONField(default=list)),
                ('include_attempt_text', models.BooleanField(default=False)),
                ('expected_heads', models.JSONField(default=list)),
                ('expected_dependencies', models.JSONField(default=list)),
                ('review_pointers', models.JSONField(default=list)),
                ('prompt_version', models.CharField(default='study-workbench.ai.prompt.v1', max_length=40)),
                ('schema_version', models.CharField(default='study-workbench.ai.v1', max_length=48)),
                ('request_key', models.CharField(max_length=160)),
                ('fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('awaiting_review', 'Awaiting review'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('stale', 'Stale'), ('applied', 'Applied')], default='queued', max_length=20)),
                ('response', models.JSONField(blank=True, null=True)),
                ('tool_results', models.JSONField(default=list)),
                ('usage', models.JSONField(default=dict)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('reserved_cost', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('error_code', models.CharField(blank=True, max_length=48)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('call_started_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('output_revision_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_model_runs', to=settings.AUTH_USER_MODEL)),
                ('attempt_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_model_runs', to='persistence.revisionrecord')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='ai.modelconfig')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_model_runs', to='persistence.household')),
            ],
            options={
                'db_table': 'ai_modelrun',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ModelBudgetReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_calls', models.PositiveSmallIntegerField(default=1)),
                ('reserved_cost', models.DecimalField(decimal_places=6, max_digits=14)),
                ('actual_calls', models.PositiveSmallIntegerField(default=0)),
                ('actual_cost', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('state', models.CharField(choices=[('held', 'Held'), ('settled', 'Settled'), ('unknown', 'Outcome unknown'), ('released', 'Released')], default='held', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_reservations', to='ai.modelconfig')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='budget_reservation', to='ai.modelrun')),
            ],
            options={
                'db_table': 'ai_budgetreservation',
            },
        ),
        migrations.AddConstraint(
            model_name='modelconfig',
            constraint=models.UniqueConstraint(fields=('household', 'revision_no'), name='ai_modelconfig_version'),
        ),
        migrations.AddConstraint(
            model_name='modelconfig',
            constraint=models.CheckConstraint(condition=models.Q(('revision_no__gt', 0)), name='ai_modelconfig_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='modelconfig',
            constraint=models.CheckConstraint(condition=models.Q(('timeout_seconds__gte', 1), ('timeout_seconds__lte', 60)), name='ai_modelconfig_timeout_bound'),
        ),
        migrations.AddConstraint(
            model_name='modelconfig',
            constraint=models.CheckConstraint(condition=models.Q(('max_output_tokens__gte', 1), ('max_output_tokens__lte', 2000)), name='ai_modelconfig_output_bound'),
        ),
        migrations.AddConstraint(
            model_name='modelconfig',
            constraint=models.CheckConstraint(condition=models.Q(('max_input_chars__gte', 1), ('max_input_chars__lte', 16000)), name='ai_modelconfig_input_bound'),
        ),
        migrations.AddConstraint(
            model_name='modelconfig',
            constraint=models.CheckConstraint(condition=models.Q(('max_calls__gte', 1), ('max_calls__lte', 4)), name='ai_modelconfig_calls_bound'),
        ),
        migrations.AddConstraint(
            model_name='modelconfig',
            constraint=models.CheckConstraint(condition=models.Q(('batch_budget__gte', 0)), name='ai_modelconfig_budget_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='modelconfig',
            constraint=models.CheckConstraint(condition=models.Q(('input_price_per_million__gte', 0)), name='ai_modelconfig_input_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='modelconfig',
            constraint=models.CheckConstraint(condition=models.Q(('output_price_per_million__gte', 0)), name='ai_modelconfig_output_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='modelconfig',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_per_call__gte', 0)), name='ai_modelconfig_reserve_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='modelconfig',
            constraint=models.CheckConstraint(condition=models.Q(('outbound_scope__in', ('reviewed_text', 'selected_regions'))), name='ai_modelconfig_scope_valid'),
        ),
        migrations.AddConstraint(
            model_name='modelconfig',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'USD')), name='ai_modelconfig_currency_fixed'),
        ),
        migrations.AddIndex(
            model_name='modelrun',
            index=models.Index(fields=['household', 'status', 'created_at'], name='ai_modelrun_queue'),
        ),
        migrations.AddConstraint(
            model_name='modelrun',
            constraint=models.UniqueConstraint(fields=('household', 'request_key'), name='ai_modelrun_request_unique'),
        ),
        migrations.AddConstraint(
            model_name='modelrun',
            constraint=models.CheckConstraint(condition=models.Q(('task_kind__in', ('question', 'knowledge', 'assessment', 'variant'))), name='ai_modelrun_task_valid'),
        ),
        migrations.AddConstraint(
            model_name='modelrun',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('queued', 'running', 'awaiting_review', 'failed', 'cancelled', 'stale', 'applied'))), name='ai_modelrun_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='modelrun',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_cost__gte', 0)), name='ai_modelrun_reserved_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='modelrun',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_cost__isnull', True), ('estimated_cost__gte', 0), _connector='OR'), name='ai_modelrun_estimated_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='modelbudgetreservation',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_calls__gte', 1)), name='ai_budget_calls_positive'),
        ),
        migrations.AddConstraint(
            model_name='modelbudgetreservation',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_cost__gte', 0)), name='ai_budget_reserved_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='modelbudgetreservation',
            constraint=models.CheckConstraint(condition=models.Q(('actual_cost__gte', 0)), name='ai_budget_actual_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='modelbudgetreservation',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('held', 'settled', 'unknown', 'released'))), name='ai_budget_state_valid'),
        ),
    ]
