# Generated by Django 5.2.17 on 2026-10-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='execution_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
