# Generated by Django 5.2.17 on 2026-10-02 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persistence', '0004_business_receipts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAnswerRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_no', models.PositiveIntegerField()),
                ('body', models.TextField()),
                ('formulas', models.JSONField(default=list)),
                ('basis', models.TextField()),
                ('source_refs', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persistence.household')),
                ('previous', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='printing.teacheranswerrevision')),
                ('question_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persistence.revisionrecord')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('withdrawn', 'withdrawn')], max_length=16)),
                ('reason', models.TextField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('previous', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='printing.answerdecision')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='printing.teacheranswerrevision')),
            ],
        ),
        migrations.CreateModel(
            name='ExportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_id', models.CharField(max_length=64)),
                ('purpose', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('storage_key', models.CharField(max_length=300)),
                ('manifest_sha256', models.CharField(max_length=64)),
                ('provenance', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persistence.household')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('household', 'export_id'), name='swb_print_identity')],
            },
        ),
        migrations.AddConstraint(
            model_name='teacheranswerrevision',
            constraint=models.UniqueConstraint(fields=('question_revision', 'revision_no'), name='swb_answer_version'),
        ),
        migrations.AddConstraint(
            model_name='teacheranswerrevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision_no__gt', 0)), name='swb_answer_positive'),
        ),
        migrations.AddConstraint(
            model_name='answerdecision',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ('accepted', 'rejected', 'withdrawn'))), name='swb_answer_decision_valid'),
        ),
    ]
