import { cleanup, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, expect, it, vi } from 'vitest'
import { DocumentCatalogue } from './catalogue'
import { notifyLearningUpdate } from '../../lib/learning-updates'

afterEach(() => { cleanup(); vi.unstubAllGlobals() })
const data = (title: string) => ({ schema_version: 'swb.api.v1', items: [{ id: title, title, category_label: '练习', created_at: '2026-10-06T00:00:00Z', state_label: '已生成', detail_url: '/prints/', message: '', zip_url: null, checks: { word_pc: { status: 'not_tested' } }, documents: [] }], total: 1, page: 1, has_next: false })
it('ignores a late previous-family response and refreshes only its own scope', async () => {
  let previous!: (response: Response) => void
  const fetcher = vi.fn().mockImplementationOnce(() => new Promise<Response>((resolve) => { previous = resolve })).mockResolvedValue(new Response(JSON.stringify(data('家庭 B 成果'))))
  vi.stubGlobal('fetch', fetcher)
  const unauthorized = vi.fn()
  const view = render(<DocumentCatalogue householdId='a' onUnauthorized={unauthorized} />)
  view.rerender(<DocumentCatalogue householdId='b' onUnauthorized={unauthorized} />)
  await screen.findByRole('heading', { name: '家庭 B 成果' })
  previous(new Response(JSON.stringify(data('家庭 A 私有成果'))))
  await waitFor(() => expect(screen.queryByText('家庭 A 私有成果')).toBeNull())
  expect((fetcher.mock.calls[0][1] as RequestInit).signal?.aborted).toBe(true)
  notifyLearningUpdate({ householdId: 'a' })
  expect(fetcher).toHaveBeenCalledTimes(2)
  fetcher.mockResolvedValue(new Response(JSON.stringify(data('家庭 B 更新'))))
  notifyLearningUpdate({ householdId: 'b' })
  await screen.findByRole('heading', { name: '家庭 B 更新' })
})
it('distinguishes no match and restores results after clearing filters without changing household scope', async () => {
  const fetcher = vi.fn(async (input: RequestInfo | URL) => {
    const url = new URL(String(input), 'http://localhost')
    return url.searchParams.get('q') ? Response.json({ schema_version: 'swb.api.v1', items: [], total: 0, page: 1, has_next: false }) : Response.json(data('合成成果'))
  })
  vi.stubGlobal('fetch', fetcher)
  render(<DocumentCatalogue householdId='a' onUnauthorized={vi.fn()} />)
  await screen.findByText(/Microsoft Word 尚未实开/)
  await userEvent.selectOptions(screen.getByLabelText('成果类型'), 'practice')
  await waitFor(() => expect(fetcher).toHaveBeenCalledTimes(2))
  await userEvent.type(screen.getByRole('searchbox'), '分数')
  await userEvent.click(screen.getByRole('button', { name: '查找成果' }))
  await screen.findByRole('heading', { name: '当前筛选没有匹配成果' })
  expect(screen.getByText('已有文档仍保留。清除筛选可查看其他成果。')).toBeTruthy()
  expect((screen.getByRole('searchbox') as HTMLInputElement).value).toBe('分数')
  expect((screen.getByLabelText('成果类型') as HTMLSelectElement).value).toBe('practice')
  expect(screen.queryByRole('button', { name: '清除筛选' })).toBeNull()
  const url = new URL(fetcher.mock.calls.at(-1)![0] as string, 'http://localhost')
  expect(url.searchParams.get('q')).toBe('分数')
  expect(url.searchParams.get('household')).toBe('a')
  expect(url.searchParams.get('category')).toBe('practice')
  await userEvent.click(screen.getByRole('button', { name: '清除筛选查看全部成果' }))
  await screen.findByRole('heading', { name: '合成成果' })
  expect((screen.getByRole('searchbox') as HTMLInputElement).value).toBe('')
  expect((screen.getByLabelText('成果类型') as HTMLSelectElement).value).toBe('')
  const clearedUrl = new URL(fetcher.mock.calls.at(-1)![0] as string, 'http://localhost')
  expect(clearedUrl.searchParams.get('q')).toBe('')
  expect(clearedUrl.searchParams.get('category')).toBe('')
  expect(clearedUrl.searchParams.get('household')).toBe('a')
})
