# Generated by Django 5.2.17 on 2026-10-02 17:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persistence', '0004_business_receipts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_schedules', to='persistence.household')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_schedules', to='persistence.entityrecord')),
                ('target_question_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_schedules', to='persistence.revisionrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_no', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('planned', 'Planned'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=16)),
                ('due_date', models.DateField()),
                ('goal', models.CharField(max_length=1200)),
                ('prompt_plan', models.TextField(blank=True)),
                ('reason', models.CharField(max_length=1000)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('completed_attempt_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_study_schedules', to='persistence.revisionrecord')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_revisions', to='study.schedulerevision')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='study.studyschedule')),
            ],
            options={
                'ordering': ('schedule_id', 'revision_no'),
            },
        ),
        migrations.CreateModel(
            name='VariantProvenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=160)),
                ('generated_text', models.TextField()),
                ('answer_expression', models.CharField(max_length=512)),
                ('check_expression', models.CharField(max_length=512)),
                ('source_revision_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_provenance', to='persistence.household')),
                ('parent_question_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_variants', to='persistence.revisionrecord')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='variant_provenance', to='persistence.entityrecord')),
                ('target_method_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_method_variants', to='persistence.revisionrecord')),
            ],
        ),
        migrations.AddIndex(
            model_name='studyschedule',
            index=models.Index(fields=['household', 'created_at'], name='study_schedule_recent'),
        ),
        migrations.AddConstraint(
            model_name='studyschedule',
            constraint=models.UniqueConstraint(fields=('household', 'schedule_id'), name='study_schedule_identity'),
        ),
        migrations.AddConstraint(
            model_name='schedulerevision',
            constraint=models.UniqueConstraint(fields=('schedule', 'revision_no'), name='study_schedule_version'),
        ),
        migrations.AddConstraint(
            model_name='schedulerevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision_no__gt', 0)), name='study_schedule_positive'),
        ),
        migrations.AddConstraint(
            model_name='schedulerevision',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ('planned', 'rescheduled', 'cancelled', 'completed'))), name='study_schedule_action_valid'),
        ),
        migrations.AddIndex(
            model_name='variantprovenance',
            index=models.Index(fields=['household', 'created_at'], name='study_variant_recent'),
        ),
    ]
