# Generated by Django 5.2.17 on 2026-10-02 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persistence', '0004_business_receipts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionLineage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('split', 'Split'), ('merge', 'Merge')], max_length=8)),
                ('source_revision_ids', models.JSONField()),
                ('target_revision_ids', models.JSONField()),
                ('reason', models.TextField()),
                ('recorded_at', models.DateTimeField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_lineage', to='persistence.household')),
            ],
            options={
                'db_table': 'catalogue_questionlineage',
                'constraints': [models.CheckConstraint(condition=models.Q(('action__in', ('split', 'merge'))), name='swb_lineage_action_valid'), models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='swb_lineage_reason_required')],
            },
        ),
    ]
