# Generated by Django 5.2.17 on 2026-10-04 17:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workbench_web', '0004_page_reading_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('content', models.JSONField()),
                ('content_hash', models.CharField(max_length=64)),
                ('sources', models.JSONField()),
                ('source_stamp', models.CharField(max_length=64)),
                ('request_key', models.CharField(max_length=160)),
                ('fingerprint', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solution_revisions', to='workbench_web.materialset')),
            ],
            options={
                'ordering': ('version',),
            },
        ),
        migrations.CreateModel(
            name='SolutionOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_key', models.CharField(max_length=160)),
                ('fingerprint', models.CharField(max_length=64)),
                ('state', models.CharField(default='queued', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('result', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('started_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outputs', to='solutions.solutionrevision')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmations', to='solutions.solutionrevision')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=160)),
                ('basis', models.CharField(max_length=1000)),
                ('source', models.JSONField(null=True)),
                ('storage_key', models.CharField(max_length=240)),
                ('sha256', models.CharField(max_length=64)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('request_key', models.CharField(max_length=160)),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solution_assets', to='workbench_web.materialset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('material', 'request_key'), name='swb_solution_asset_request')],
            },
        ),
        migrations.CreateModel(
            name='SolutionOutputEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=32)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='solutions.solutionoutput')),
            ],
            options={
                'ordering': ('version',),
                'constraints': [models.UniqueConstraint(fields=('output', 'version'), name='swb_solution_output_event')],
            },
        ),
        migrations.AddConstraint(
            model_name='solutionrevision',
            constraint=models.UniqueConstraint(fields=('material', 'version'), name='swb_solution_revision_version'),
        ),
        migrations.AddConstraint(
            model_name='solutionrevision',
            constraint=models.UniqueConstraint(fields=('material', 'request_key'), name='swb_solution_revision_request'),
        ),
        migrations.AddConstraint(
            model_name='solutionoutput',
            constraint=models.UniqueConstraint(fields=('revision', 'request_key'), name='swb_solution_output_request'),
        ),
        migrations.AddConstraint(
            model_name='solutionoutput',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('queued', 'running', 'output_check', 'complete', 'failed', 'cancelled'))), name='swb_solution_output_state'),
        ),
    ]
