# Generated by Django 5.2.17 on 2026-10-05 12:52

from django.conf import settings
from django.db import migrations, models

SQL = """
CREATE FUNCTION swb_companion_revision_insert_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE old_version integer; house text;
BEGIN
  SELECT household_id INTO house FROM workbench_web_materialset WHERE id=NEW.material_id FOR UPDATE;
  SELECT version INTO old_version FROM solutions_solutionrevision
    WHERE material_id=NEW.material_id AND mode=NEW.mode ORDER BY version DESC LIMIT 1;
  IF NEW.version IS DISTINCT FROM COALESCE(old_version,0)+1 THEN
    RAISE EXCEPTION 'Companion revisions must append the current mode history';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM swb_householdmember m JOIN auth_user u ON u.id=m.user_id
    WHERE m.household_id=house AND m.user_id=NEW.author_id AND m.role IN ('owner','reviewer') AND u.is_active)
    OR btrim(NEW.reason)='' OR btrim(NEW.request_key)='' THEN
    RAISE EXCEPTION 'Companion author is unauthorized';
  END IF;
  IF (NEW.mode='knowledge' AND COALESCE(NEW.content->>'schema_version','')<>'swb.knowledge.v1') OR
     (NEW.mode='solution' AND COALESCE(NEW.content->>'schema_version','') NOT IN
       ('swb.solution.v1','swb.solution.v2','swb.solution.v3')) THEN
    RAISE EXCEPTION 'Companion mode and content schema differ';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER swb_companion_revision_insert BEFORE INSERT ON solutions_solutionrevision
  FOR EACH ROW EXECUTE FUNCTION swb_companion_revision_insert_guard();
"""
REVERSE = """
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM solutions_solutionrevision
    WHERE mode='knowledge' OR content->>'schema_version'='swb.solution.v3') THEN
    RAISE EXCEPTION 'Restore a matching backup rather than discarding newer companion histories';
  END IF;
END $$;
DROP TRIGGER swb_companion_revision_insert ON solutions_solutionrevision;
DROP FUNCTION swb_companion_revision_insert_guard();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_history_guards'),
        ('workbench_web', '0005_materialclassificationrevision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='solutionrevision',
            name='swb_solution_revision_version',
        ),
        migrations.RemoveConstraint(
            model_name='solutionrevision',
            name='swb_solution_revision_request',
        ),
        migrations.AddField(
            model_name='solutionrevision',
            name='mode',
            field=models.CharField(default='solution', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='solutionrevision',
            constraint=models.UniqueConstraint(fields=('material', 'mode', 'version'), name='swb_solution_revision_mode_version'),
        ),
        migrations.AddConstraint(
            model_name='solutionrevision',
            constraint=models.UniqueConstraint(fields=('material', 'mode', 'request_key'), name='swb_solution_revision_mode_request'),
        ),
        migrations.AddConstraint(
            model_name='solutionrevision',
            constraint=models.CheckConstraint(condition=models.Q(('mode__in', ('solution', 'knowledge'))), name='swb_companion_mode'),
        ),
        migrations.RunSQL(SQL, REVERSE),
    ]
