# Generated by Django 5.2.17 on 2026-10-02 06:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persistence', '0002_postgresql_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset_key', models.CharField(max_length=160)),
                ('source_digest', models.CharField(max_length=64)),
                ('prepared_at', models.DateTimeField()),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('manifest', models.JSONField()),
                ('counts', models.JSONField()),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persistence.household')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='persistence.requestreceipt')),
            ],
            options={
                'db_table': 'swb_legacyimportbatch',
            },
        ),
        migrations.CreateModel(
            name='LegacyIndexEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('book', models.CharField(max_length=8)),
                ('number', models.CharField(max_length=40)),
                ('raw', models.JSONField()),
                ('photo_tokens', models.JSONField()),
                ('auxiliary_method_revision_ids', models.JSONField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='imports.legacyimportbatch')),
                ('primary_method_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_classifications', to='persistence.revisionrecord')),
                ('question_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_entries', to='persistence.revisionrecord')),
            ],
            options={
                'db_table': 'swb_legacyindexentry',
            },
        ),
        migrations.AddConstraint(
            model_name='legacyimportbatch',
            constraint=models.UniqueConstraint(fields=('household', 'dataset_key'), name='swb_import_house_dataset_uniq'),
        ),
        migrations.AddConstraint(
            model_name='legacyimportbatch',
            constraint=models.CheckConstraint(condition=models.Q(('source_digest__regex', '^[0-9a-f]{64}$')), name='swb_import_digest_valid'),
        ),
        migrations.AddConstraint(
            model_name='legacyindexentry',
            constraint=models.UniqueConstraint(fields=('batch', 'book', 'number'), name='swb_import_entry_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='legacyindexentry',
            constraint=models.UniqueConstraint(fields=('batch', 'ordinal'), name='swb_import_entry_order_uniq'),
        ),
        migrations.AddConstraint(
            model_name='legacyindexentry',
            constraint=models.CheckConstraint(condition=models.Q(('ordinal__gt', 0)), name='swb_import_entry_order_positive'),
        ),
    ]
